from __future__ import annotations

import asyncio
from pathlib import Path

from patchright.async_api import Page as AsyncPage

from utils import (
    async_browser_session,
    async_update_state,
    cdp_is_up,
    start_browser,
)

# --------------------------------------------------------------------------
# URLs
# --------------------------------------------------------------------------

YT_HOME_URL = "https://www.youtube.com/"
YT_STUDIO_URL = "https://studio.youtube.com/"


# --------------------------------------------------------------------------
# Studio navigation
# --------------------------------------------------------------------------
# The browser is already logged in and cookies are shared across every
# session that attaches to the CDP profile (see start_browser() /
# async_browser_session() in utils.py) - so the click-through-the-menu
# path (avatar -> "YouTube Studio") isn't actually required to reach
# Studio. open_studio() below just navigates straight there. Keeping
# click_to_studio() around as a fallback for verifying the manual UI
# path still works, or for a cold profile where cookies haven't landed.


async def open_studio(page: AsyncPage) -> None:
    """*Usage:*
    >>> async with async_browser_session() as session:
    ...     await open_studio(session.page)
    """
    await page.goto(YT_STUDIO_URL, wait_until="domcontentloaded")


async def click_to_studio(page: AsyncPage) -> None:
    """
    Fallback path that mimics the manual click-through.

    NOTE: the dropdown's link to Studio uses id="endpoint", but every
    ytd-compact-link-renderer on the page reuses that same id - it is
    not unique. Clicking "#endpoint" directly raises Playwright's
    strict-mode error ("multiple elements match"). Filter by the
    link's visible text instead, as done below.

    *Usage:*
    >>> async with async_browser_session() as session:
    ...     await click_to_studio(session.page)
    """
    await page.goto(YT_HOME_URL, wait_until="domcontentloaded")
    await page.click("#avatar-btn")
    await page.get_by_text("YouTube Studio", exact=True).click()
    await page.wait_for_url(f"{YT_STUDIO_URL}*")


# --------------------------------------------------------------------------
# Studio left-nav (Dashboard / Content / Analytics / ...)
# --------------------------------------------------------------------------
# CAUTION: menu-paper-icon-item-0, -1, -2... are positional ids, not
# semantic ones. They line up with Dashboard/Content/Analytics/... in
# that order only because that's what's enabled for this channel. A
# channel with a different feature set (e.g. no "Content detection")
# has a shorter list, and everything after it silently shifts down one
# slot. Filtering by the item's own text (below) survives that; the
# raw ids from your notes would not.

STUDIO_NAV_LABELS = [
    "Dashboard",
    "Content",
    "Analytics",
    "Community",
    "Subtitles",
    "Content detection",
    "Earn",
    "Customization",
    "Audio library",
]


async def goto_studio_section(page: AsyncPage, label: str) -> None:
    """*Usage:*
    >>> async with async_browser_session() as session:
    ...     await open_studio(session.page)
    ...     await goto_studio_section(session.page, "Content")
    """
    if label == "Settings":
        await page.click("#settings-item")
        return
    await page.locator("tp-yt-paper-item", has_text=label).first.click()


# --------------------------------------------------------------------------
# Upload
# --------------------------------------------------------------------------
# CAUTION: the "Upload videos" button on the dashboard's empty-state
# card (the one under "Want to see metrics on your recent video?")
# only exists before the channel has any videos - it disappears for
# good after the first upload. Don't build around it. The persistent
# entry point is the "Create" control in Studio's top bar (#upload-icon
# per your notes), which is there regardless of upload history.


async def upload_video(
    page: AsyncPage,
    video_path: str | Path,
    progress=None,
) -> None:
    """
    Opens the native file picker via Studio's persistent upload
    control and hands it the video file. Stops once the details wizard
    opens - filling in title/description/visibility/publish is a TODO
    once you've mapped those selectors (they're dynamic per step, so
    grab them from the DOM the same way you did for the ones above).

    expect_file_chooser() intercepts the browser's file-chooser event
    directly, so there's no need for the goog_-prefixed "Select files"
    id from your notes - that id is autogenerated by Closure per page
    load and won't exist under that name on the next run anyway.

    *Usage:*
    >>> async with async_browser_session() as session:
    ...     await open_studio(session.page)
    ...     await upload_video(session.page, "videos/my_video.mp4")
    """
    video_path = Path(video_path)
    if not video_path.exists():
        raise FileNotFoundError(video_path)

    if progress:
        await progress(message="Opening upload dialog...")

    async with page.expect_file_chooser() as fc_info:
        await page.click("#upload-icon")
        # If #upload-icon opens a "Create" dropdown rather than the
        # file picker directly, uncomment the line below - you already
        # have the locator for it in your notes:
        # await page.get_by_label("Upload videos").click()
    file_chooser = await fc_info.value
    await file_chooser.set_files(str(video_path))

    if progress:
        await progress(message="File selected, waiting for upload to start...")

    # TODO: fill in title/description, step through "Next" x3, set
    # visibility, hit Publish/Save. Selectors not mapped yet - inspect
    # the wizard's DOM the same way you did for the steps above.


# --------------------------------------------------------------------------
# End-to-end run (what app.py calls)
# --------------------------------------------------------------------------


async def run_upload(video_path: str | Path, browser: str = "brave") -> None:
    """*Usage:*
    >>> asyncio.run(run_upload("videos/my_video.mp4"))
    """
    if not cdp_is_up():
        await asyncio.to_thread(lambda: start_browser(browser).close())

    async with async_update_state("yt_upload", total=3) as progress:
        async with async_browser_session() as session:
            await progress(current=1, message="Opening YouTube Studio...")
            await open_studio(session.page)

            await progress(current=2, message="Uploading video...")
            await upload_video(session.page, video_path, progress=progress)

            await progress(current=3, message="Upload started.")


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: python yt.py <path-to-video>")
        raise SystemExit(1)
    asyncio.run(run_upload(sys.argv[1]))